# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Gradle JVM settings (optional but recommended)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin compiler settings (if you add Kotlin later)
kotlin.incremental=true
kotlin.code.style=official

# Gradle parallel builds (faster)
org.gradle.parallel=true

# Enable caching to speed up builds
org.gradle.caching=true

org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
